title: Jekyll Demo Site
email: demo@example.com
description: >
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: 'http://jekyll-demo.com'
markdown: kramdown
permalink: '/:title.html'
source: ./src
destination: ./public
plugins_dir: ./src/_plugins
layouts_dir: ./src/_layouts
data_dir: ./src/_data
includes_dir: ./src/_includes
collections:
  music:
    output: true
    layout: null
host: 127.0.0.1
port: 4000
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      author: Mr. Author
      permalink: '/blog/:title'
  - scope:
      type: music
    values:
      layout: music
      permalink: '/music/:title'
