---
title: Jekyll Demo Site
timezone: UTC
collections:
  music:
    title: Music
    output: true
    layout: music
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Mr. Author
    permalink: "/blog/:title"
- scope:
    path: ''
    type: music
  values:
    layout: music
    permalink: "/music/:title"
email: demo@example.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ''
url: http://jekyll-demo.com
markdown: kramdown
permalink: "/:title.html"
destination: "./_site"
plugins_dir: "./_plugins"
layouts_dir: "./_layouts"
data_dir: "./_data"
includes_dir: "./_includes"
host: 127.0.0.1
port: 4000
